Sigmoid関数とSoftmax関数の実装

In [2]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

def softMax(x):
    exp_x = np.exp(x)
    exp_x_sum = np.sum(exp_a)
    return exp_x/exp_x_sum

３層のNNの実装

In [7]:
def init_network():
    network={}
    network['W1'] = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
    network['b1'] = np.array([[0.1, 0.2, 0.3]])
    network['W2'] = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
    network['b2'] = np.array([[0.1, 0.2]])
    network['W3'] = np.array([[0.1, 0.3], [0.2, 0.4]])
    network['b3'] = np.array([[0.1, 0.2]])
    return network

def forward(network, x):
    # layer 1
    W1=network['W1']
    b1=network['b1']
    a1=np.dot(x,W1)+b1
    z1=sigmoid(a1)
    
    # layer 2
    W2=network['W2']
    b2=network['b2']
    a2=np.dot(z1, W2)+b2
    z2=sigmoid(a2)
    
    # layer 3
    W3=network['W3']
    b3=network['b3']
    a3=np.dot(z2, W3)+b3
    y=a3
    
    # output
    return y

network = init_network()
x=np.array([1.0,0.5])
y=forward(network,x)
print(y) #[0.31682708 0.69627909]

[[0.31682708 0.69627909]]


バッチ処理

In [29]:
import numpy as np
import random  
network = init_network()
batch_size = 16
x=np.random.rand(1000,2)
for i in range(0,len(x),batch_size):
    x_batch = x[i:i+batch_size]
    y_batch = forward(network,x_batch)

In [30]:
x.shape 

(1000, 2)

xは1000行2列の行列

In [32]:
x[0].shape

(2,)

In [33]:
x

array([[0.52592021, 0.99970368],
       [0.89196032, 0.46603786],
       [0.76677459, 0.96804063],
       ...,
       [0.65295821, 0.0667835 ],
       [0.87562934, 0.1837645 ],
       [0.71593092, 0.22500995]])

In [34]:
x[0:0+batch_size]

array([[0.52592021, 0.99970368],
       [0.89196032, 0.46603786],
       [0.76677459, 0.96804063],
       [0.86474359, 0.10554863],
       [0.33547394, 0.10491013],
       [0.14699263, 0.14270444],
       [0.44802424, 0.34848792],
       [0.23641627, 0.42123804],
       [0.94095255, 0.30709662],
       [0.32664406, 0.38483573],
       [0.18598075, 0.485633  ],
       [0.15523175, 0.55621103],
       [0.10606148, 0.34837015],
       [0.13281913, 0.73133696],
       [0.46195187, 0.71205662],
       [0.67417557, 0.58525723]])

x[0]からx[15]までの16行2列の行列　

In [26]:
forward(network,x[0:0+batch_size])

array([[0.3127398 , 0.68719056],
       [0.31539014, 0.69307831],
       [0.31506784, 0.69235737],
       [0.31903779, 0.70118995],
       [0.31426406, 0.69057613],
       [0.31510546, 0.69244927],
       [0.31454464, 0.69119673],
       [0.31560079, 0.69355559],
       [0.31347312, 0.68882115],
       [0.31558588, 0.69351731],
       [0.3130645 , 0.68791543],
       [0.31146532, 0.68437339],
       [0.31788454, 0.69862567],
       [0.31826722, 0.6994752 ],
       [0.31428517, 0.69062161],
       [0.31093107, 0.68317677]])

In [36]:
forward(network, x[0])

array([[0.31764356, 0.69808238]])

16個のデータをまとめて計算したが、それぞれの計算に影響はでていないことがわかる。

感想  
ニューラルネットワークの原型ができた。バッチという言葉は聞いたことがあったが、詳しく知らなかったので実際に試してみて理解できた。おそらく次は学習に入るので楽しみです。

参考文献  
ゼロから作るDeepLearning　３章　ニューラルネットワーク